# Generated by Django 4.0.5 on 2023-12-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_project_votes_ratio_project_votes_total_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='icon.svg', null=True, upload_to=''),
        ),
    ]
